name: spbee
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_widgets: ^1.1.0
  audioplayers: ^6.5.0
  flutter_tts: ^4.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sounds/next-level.mp3
    - assets/sounds/reject.mp3
    # - assets/spelling/jun/
    # - assets/spelling/middle/
    # - assets/spelling/senior/
