name: spbee
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_widgets: ^1.1.0
  audioplayers: ^6.5.0
  flutter_tts: ^4.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sounds/next-level.mp3
    - assets/sounds/reject.mp3
    # - assets/spelling/jun/
    # - assets/spelling/middle/
    # - assets/spelling/senior/


  fonts:
    - family: Atyp
      fonts:
        - asset: assets/fonts/atyp/AtypDisplay-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/atyp/AtypDisplay-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/atyp/AtypDisplay-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/atyp/AtypDisplay-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/atyp/AtypDisplay-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/atyp/AtypDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/atyp/AtypDisplay-Semibold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/atyp/AtypDisplay-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/atyp/AtypDisplay-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/atyp/AtypDisplay-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/atyp/AtypDisplay-Bold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/atyp/AtypDisplay-BoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/atyp/AtypDisplay-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/atyp/AtypDisplay-ThinItalic.ttf
          style: italic
          weight: 100

